-- MySQL Script generated by MySQL Workbench
-- Ben 16 D-Ɔ 2021 20:15:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`certification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`certification` (
  `certification_id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`certification_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fields`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fields` (
  `fields_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`fields_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`skills` (
  `skills_id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `fields_fields_id` INT NOT NULL,
  PRIMARY KEY (`skills_id`),
  INDEX `fk_skills_fields1_idx` (`fields_fields_id` ASC) VISIBLE,
  CONSTRAINT `fk_skills_fields1`
    FOREIGN KEY (`fields_fields_id`)
    REFERENCES `mydb`.`fields` (`fields_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`experience` (
  `experience_id` INT NOT NULL,
  `institution` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  `duration` VARCHAR(45) NULL,
  PRIMARY KEY (`experience_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`education`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`education` (
  `education_id` INT NOT NULL,
  `institution` VARCHAR(45) NULL,
  `major` VARCHAR(45) NULL,
  `completion_date` DATE NULL,
  PRIMARY KEY (`education_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trainee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trainee` (
  `traineeID` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `contact` VARCHAR(45) NULL,
  `traineecol` VARCHAR(45) NULL,
  `certification_certification_id` INT NOT NULL,
  `skills_skills_id` INT NOT NULL,
  `experience_experience_id` INT NOT NULL,
  `education_education_id` INT NOT NULL,
  `is_admin` VARCHAR(45) NULL,
  PRIMARY KEY (`traineeID`),
  INDEX `fk_trainee_certification_idx` (`certification_certification_id` ASC) VISIBLE,
  INDEX `fk_trainee_skills1_idx` (`skills_skills_id` ASC) VISIBLE,
  INDEX `fk_trainee_experience1_idx` (`experience_experience_id` ASC) VISIBLE,
  INDEX `fk_trainee_education1_idx` (`education_education_id` ASC) VISIBLE,
  CONSTRAINT `fk_trainee_certification`
    FOREIGN KEY (`certification_certification_id`)
    REFERENCES `mydb`.`certification` (`certification_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trainee_skills1`
    FOREIGN KEY (`skills_skills_id`)
    REFERENCES `mydb`.`skills` (`skills_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trainee_experience1`
    FOREIGN KEY (`experience_experience_id`)
    REFERENCES `mydb`.`experience` (`experience_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trainee_education1`
    FOREIGN KEY (`education_education_id`)
    REFERENCES `mydb`.`education` (`education_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
